plan  <-  drake::drake_plan(
  # Data -------------------------------------------------
  POM_all = read.csv("data/data_Tanioka22_NatCom_POM_all.csv"),                           # all POM data after selection
  POM_genomes_selected = read.csv("data/data_Tanioka22_NatCom_POM_genomes_selected.csv"), # POM data paired with genome-based nut limitation
  POM_ver1_surface_binned = read.csv("data/data_Tanioka22_NatCom_POM_ver1_surface_binned_1deg.csv") %>%
    mutate(Nutlim = sp_Nutlim_CESM2), # POM data version 1 surface binned
  # Data wrangling for various analyses ------------------
  POM_all_binned = bin_data_1by1(POM_all), 
  POM_genomes_selected_binned = bin_data_1by1(POM_genomes_selected), 
  POM_genomes_selected_binned_w_highlat = make_obsNutlim_overlay_cesm(POM_all_binned,
                                                                     POM_genomes_selected_binned),
  POM_all_gam = clean_data_for_gam(POM_all), 
  POM_genomes_selected_gam = clean_data_for_gam(POM_genomes_selected),
  POM_ver1_surface_binned_gam = clean_data_for_gam(POM_ver1_surface_binned),
  POM_genomes_selected_gam_w_highlat = combine_data_global_gam(POM_all_gam,
							       POM_genomes_selected_gam),
  POM_highlat_gam = POM_all_gam %>% sep_data_highlat(latitude = 45),
  POM_lowlat_gam = POM_genomes_selected_gam %>% sep_data_lowlat(latitude = 45),
  POM_highlat_ver1_surface_binned_gam = POM_ver1_surface_binned_gam %>% sep_data_highlat(latitude = 45),
  POM_lowlat_ver1_surface_binned_gam = POM_ver1_surface_binned_gam %>% sep_data_lowlat(latitude = 45),
  scaled.POM_highlat_corr = clean_data_for_corr(sep_data_highlat(POM_all, latitude = 45)),
  scaled.POM_lowlat_corr = clean_data_for_corr(sep_data_lowlat(POM_all, latitude = 45)),
  # CESM2-LENS Data--------------------------------------
  cesm_filepath = "data/CESM2_lens",
  sst_surf_historic = read_sst_cesm(cesm_filepath, 'TEMP_regrid_historic.nc'),
  sst_surf_SSP370 = read_sst_cesm(cesm_filepath, 'TEMP_regrid_SSP370.nc'),
  nutcline_historic = read_nutcline_cesm(cesm_filepath, 'Nutcline_regrid_historic.nc',
                                        nutcline_correction = 1.54),
  nutcline_historic_uncorrected = read_nutcline_cesm(cesm_filepath, 'Nutcline_regrid_historic.nc',
                                        nutcline_correction = 1.0),
  nutcline_SSP370 = read_nutcline_cesm(cesm_filepath, 'Nutcline_regrid_SSP370.nc',
                                      nutcline_correction = 1.54),
  nitrate_surf_historic = read_nitrate_cesm(cesm_filepath, 'NO3_regrid_historic.nc', 
					    threshold = 0.1),
  nitrate_surf_SSP370 = read_nitrate_cesm(cesm_filepath, 'NO3_regrid_SSP370.nc', 
					  threshold = 0.1),
  nutlim_historic = read_nutlim_cesm(cesm_filepath,
                                    'sp_Nut_lim_surf_historic.nc',
                                    varid = "sp_Nut_lim_surf_historic"),
  nutlim_SSP370 = read_nutlim_cesm(cesm_filepath,
                                    'sp_Nut_lim_surf_SSP370.nc',
                                    varid = "sp_Nut_lim_surf_SSP370"),
  cesm_lonlat_info =  get_cesm_lonlat(cesm_filepath,'TEMP_regrid_historic.nc'),
  cesm_var_array_for_gam = make_cesm_var_array_for_gam(sst_surf_historic,
						       sst_surf_SSP370,
                                                       nitrate_surf_historic,
                                                       nitrate_surf_SSP370,
                                                       nutcline_historic,
                                                       nutcline_SSP370,
                                                       nutlim_historic,
                                                       nutlim_SSP370),
  # GLODAPv2.2016b Data-----------------------------------
  glodap_filepath = "data/GLODAPv2.2016b",
  glodap_lonlat_surfdepth_info = get_glodap_lonlat_surfdepth(glodap_filepath,
                                                              filename_temp = 'GLODAPv2.2016b.temperature_regrid.nc',
                                                              filename_nutcline = 'GLODAPv2.2016b.nutcline_regrid.nc',
                                                              surfdepth = 30.0),
  nutcline_glodap_data = read_nutcline_glodap(glodap_filepath, 'GLODAPv2.2016b.nutcline_regrid.nc'),
  
  # Cross validation analysis to determine best hierarchical GAMS----------------
    # Comment out if cv_CP.rda, cv_NP.rda, cv_CN.rda are already made
    # From this, we use model GI throughout to describe nutricline x nutlim interaction 
  # Option 1: Calculate them de novo (Takes about 5 minutes per cross validation) #
    # cv_cp  = cv_mod(POM_genomes_selected_gam, "CP", npartition = 100, fractest = 0.2, 
    #               file = "output/cv/cv_cp.rds"),
    # cv_np  = cv_mod(POM_genomes_selected_gam, "NP", npartition = 100, fractest = 0.2, 
    #               file = "output/cv/cv_np.rds"),
    # cv_cn  = cv_mod(POM_genomes_selected_gam, "CN", npartition = 100, fractest = 0.2, 
    #                file = "output/cv/cv_cn.rds"),
  # Option 2: Load premade cv files  to save time #
   cv_cp = readRDS("output/cv/cv_cp.rds"),
   cv_np = readRDS("output/cv/cv_np.rds"),
   cv_cn = readRDS("output/cv/cv_cn.rds"),
  
  # Analyses ---------------------------------------------
  Cruise_summary = dplyr::group_by(POM_all, Cruise),
  Summary_per_cruise = dplyr::summarize(Cruise_summary,
                                         nrows = n(),
                                         minLat = min(Latitude, na.rm = TRUE),
                                         maxLat = max(Latitude, na.rm = TRUE),
                                         minLon = min(Longitude, na.rm = TRUE),
                                         maxLon = max(Longitude, na.rm = TRUE)),
  CNP_global_mean = calc_cnp_global_mean(tibble(POM_all)),
  CNP_global_mean_binned = calc_cnp_global_mean(tibble(POM_all_binned)),
  CNP_global_mean_ver1_surface_binned = calc_cnp_global_mean(tibble(POM_ver1_surface_binned)),
  M_POM_highlat_corr_selected = M.POM_corr(scaled.POM_highlat_corr,highlat = TRUE, 
					   colnames = TRUE),
  M_POM_lowlat_corr_selected = M.POM_corr(scaled.POM_lowlat_corr,highlat = FALSE, 
					  colnames = TRUE),
  testRes_selected_highlat = testRes.POM_corr(scaled.POM_highlat_corr,highlat = TRUE),
  testRes_selected_lowlat = testRes.POM_corr(scaled.POM_lowlat_corr, highlat = FALSE),
  CNP_highlat_gam_devexpl = make_CNP_devexpl_highlat(POM_highlat_gam),
  CNP_lowlat_gam_devexpl = make_CNP_devexpl_lowlat(POM_lowlat_gam),
  CNP_highlat_gam_pval =  make_CNP_pval_highlat(POM_highlat_gam),
  CNP_lowlat_gam_pval = make_CNP_pval_lowlat(POM_lowlat_gam),
  CNP_highlat_ver1_gam_devexpl = make_CNP_devexpl_highlat(POM_highlat_ver1_surface_binned_gam),
  CNP_lowlat_ver1_gam_devexpl = make_CNP_devexpl_lowlat(POM_lowlat_ver1_surface_binned_gam),
  CNP_highlat_ver1_gam_pval =  make_CNP_pval_highlat(POM_highlat_ver1_surface_binned_gam),
  CNP_lowlat_ver1_gam_pval = make_CNP_pval_lowlat(POM_lowlat_ver1_surface_binned_gam),
  mod_CNP_no_Nutlim = make_mod_CNP_no_Nutlim(POM_genomes_selected_gam_w_highlat),
  mod_CNP_Nutcline_Nutlim_mod = make_mod_CNP_Nutcline_Nutlim_mod(POM_genomes_selected_gam_w_highlat),
  mod_CNP_Nutcline_Nutlim_mod_for_gam_cesm = make_mod_CNP_Nutcline_Nutlim_mod(POM_genomes_selected_gam_w_highlat %>% 
										  mutate_at(c("Nutlim"), 
											    replace_factor_na, 
											    factorname = "Fe-lim")),
  mod_CP = mod_CNP_Nutcline_Nutlim_mod$mod_CP_Nutcline_Nutlim_mod,
  mod_NP = mod_CNP_Nutcline_Nutlim_mod$mod_NP_Nutcline_Nutlim_mod,
  mod_CN = mod_CNP_Nutcline_Nutlim_mod$mod_CN_Nutcline_Nutlim_mod,
  mod_CP_cesm = mod_CNP_Nutcline_Nutlim_mod_for_gam_cesm$mod_CP_Nutcline_Nutlim_mod,
  mod_NP_cesm = mod_CNP_Nutcline_Nutlim_mod_for_gam_cesm$mod_NP_Nutcline_Nutlim_mod,
  mod_CN_cesm = mod_CNP_Nutcline_Nutlim_mod_for_gam_cesm$mod_CN_Nutcline_Nutlim_mod,
  CNP_gam_cesm = predict_cnp_gam_cesm(mod_CP_cesm, 
				      mod_NP_cesm, 
				      cesm_var_array_for_gam),
  diffcp_full_PosCount_grid = calc_diff_cnp_PosCount_grid(mod_CP_cesm,
                                                          m = 1000,
                                                          n = 2000,
                                                          cesm_var_array_for_gam),
  diffnp_full_PosCount_grid = calc_diff_cnp_PosCount_grid(mod_NP_cesm, 
                                                          m = 1000,
                                                          n = 2000,
                                                          cesm_var_array_for_gam),
  # Figures ----------------------------------------------
  fig_out_folder = dir.create("output/figures/",
                              recursive = TRUE,
                              showWarnings = FALSE),
  fig_1_pdf = make_map_ver1ver2(file_out("output/figures/fig_1.pdf"),
                                    fig_out_folder,
                                    POM_ver1_surface_binned,
                                    POM_all_binned),    
  fig_2_pdf = make_fig_1(file_out("output/figures/fig_2.pdf"), 
                         fig_out_folder,
                         POM_all),
  fig_3_highlat_pdf = make_fig_2(file_out("output/figures/fig_3_highlat.pdf"), 
                         fig_out_folder,
                         M_POM_highlat_corr_selected,
                         testRes_selected_highlat,
                         CNP_highlat_gam_devexpl,
                         title_name = "Polar & Subpolar"),  
  fig_3_lowlat_pdf = make_fig_2(file_out("output/figures/fig_3_lowlat.pdf"), 
                               fig_out_folder,
                               M_POM_lowlat_corr_selected,
                               testRes_selected_lowlat,
                               CNP_lowlat_gam_devexpl,
                               title_name = "Tropical & Subtropical"),  
  fig_4_pdf = make_fig_3_new(file_out("output/figures/fig_4.pdf"), 
                             fig_out_folder,
                             mod_CNP_no_Nutlim$mod_CP,
                             mod_CNP_no_Nutlim$mod_NP,
                             mod_CNP_no_Nutlim$mod_CN,
                             mod_CP,
                             mod_NP,
                             mod_CN,
                             POM_genomes_selected_gam_w_highlat,
                             POM_genomes_selected_gam),
  fig_5_pdf = make_fig_4(file_out("output/figures/fig_5.pdf"), 
			 fig_out_folder,
			 cesm_lonlat_info,
			 CNP_gam_cesm,
			 diffcp_full_PosCount_grid,
			 plot_title_topleft = "(A) DeltaC:P (2090s - 2010s, SSP3-7.0)",
			 plot_title_topright = "(B) Model agreement on the sign of DeltaC:P",
			 colbarbreak = seq(-25,25,5),
			 colbartitle = "DeltaC:P (molar)",
			 colbarlimits = c(-30,30),
			 NP = FALSE),
  ed_fig_1_pdf = make_ed_fig_2(file_out("output/figures/ed_fig_1.pdf"),
                               fig_out_folder,
                               POM_genomes_selected_binned_w_highlat,
                               nutlim_historic,
                               nutlim_SSP370,
                               cesm_lonlat_info),
  ed_fig_2_pdf = make_fig_3_NO3only(file_out("output/figures/ed_fig_2.pdf"), 
                                    fig_out_folder,
                                    mod_CNP_no_Nutlim$mod_CP,
                                    mod_CNP_no_Nutlim$mod_NP,
                                    mod_CNP_no_Nutlim$mod_CN,
                                    POM_genomes_selected_gam_w_highlat,
                                    POM_genomes_selected_gam),  
  ed_fig_3_highlat_pdf = make_fig_2b_only(file_out("output/figures/ed_fig_3_highlat.pdf"), 
                                          fig_out_folder,
                                          CNP_highlat_ver1_gam_devexpl),  
  ed_fig_3_lowlat_pdf = make_fig_2b_only(file_out("output/figures/ed_fig_3_lowlat.pdf"), 
                                         fig_out_folder,
                                         CNP_lowlat_ver1_gam_devexpl),  
  ed_fig_4_pdf = make_fig_3_new_NP(file_out("output/figures/ed_fig_4.pdf"), 
                                   fig_out_folder,
                                   mod_CNP_no_Nutlim$mod_NP,
                                   mod_NP,
                                   POM_genomes_selected_gam_w_highlat,
                                   POM_genomes_selected_gam),
  ed_fig_5_pdf = make_ed_fig_6(file_out("output/figures/ed_fig_5.pdf"),
                               fig_out_folder,
                               sst_surf_historic,
                               sst_surf_SSP370,
                               nitrate_surf_historic,
                               nitrate_surf_SSP370,
                               nutcline_historic,
                               nutcline_SSP370,
                               cesm_lonlat_info),  
  ed_fig_6_pdf = make_ed_fig_7(file_out("output/figures/ed_fig_6.pdf"), 
                               fig_out_folder,
                               cesm_lonlat_info,
                               CNP_gam_cesm,
                               POM_all_binned),
  ed_fig_7_pdf = make_fig_4(file_out("output/figures/ed_fig_7.pdf"), 
                            fig_out_folder,
                            cesm_lonlat_info,
                            CNP_gam_cesm,
                            diffnp_full_PosCount_grid,
                            plot_title_topleft = "(A) DeltaN:P (2090s - 2010s, SSP3-7.0)",
                            plot_title_topright = "(B) Model agreement on the sign of DeltaN:P",
                            colbarbreak = seq(-5,5,1),
                            colbartitle = "DeltaN:P (molar)",
                            colbarlimits = c(-6,6),
                            NP = TRUE),	  
  ed_fig_8_cp_pdf =  make_fig_delcnp_driver(file_out("output/figures/ed_fig_8_cp.pdf"),
                                         fig_out_folder,
                                         cesm_lonlat_info,
                                         CNP_gam_cesm,
                                         maintitle = "Delta C:P",
                                         colbarbreak = seq(-25,25,5),
                                         colbarlimits = c(-30,30),
                                         NP = FALSE),	  
  ed_fig_8_np_pdf =  make_fig_delcnp_driver(file_out("output/figures/ed_fig_8_np.pdf"),
                                          fig_out_folder,
                                          cesm_lonlat_info,
                                          CNP_gam_cesm,
                                          maintitle = "Delta N:P",
                                          colbarbreak = seq(-5,5,1),
                                          colbarlimits = c(-6,6),
                                          NP = TRUE),  
  ed_fig_9_pdf = make_ed_fig_1(file_out("output/figures/ed_fig_9.pdf"),
                               fig_out_folder,
                               glodap_lonlat_surfdepth_info,
                               cesm_lonlat_info,
                               nutcline_glodap_data,
                               nutcline_historic_uncorrected,
                               "(A) Nutricline (GLODAP)",
                               "(B) Nutricline (CESM, 2010s)",
                               "(C) DeltaNutricline (GLODAP - CESM)",
                               "(D)"),
  # Tables -----------------------------------------------
  tab_out_folder = {
    dir.create("output/tables/", recursive = TRUE, showWarnings = FALSE)
    "output/tables"
  },
  sp_table_2 = {
    make_cnp_table(CNP_global_mean, sgnf = 1, rownames = TRUE, 
		   tab_out_folder, "sp_table_2.csv")
  },
  sp_table_3 = {
    make_cnp_table(CNP_global_mean_binned, sgnf = 1, rownames = TRUE, 
		   tab_out_folder,  "sp_table_3.csv")
  },
  sp_table_4 = {
    make_region_cnp_summary_combined(POM_all, rownames = FALSE, 
				     tab_out_folder,  "sp_table_4.csv")
  },
  sp_table_5 = {
    make_corr_pval_table(M_POM_highlat_corr_selected , 
			 testRes_selected_highlat,
			 rownames = TRUE,
			 tab_out_folder,  "sp_table_5.csv")
  },
  sp_table_6 = {
    make_corr_pval_table(M_POM_lowlat_corr_selected , 
			 testRes_selected_lowlat,
			 rownames = TRUE,
			 tab_out_folder,  "sp_table_6.csv")
  },
  sp_table_7 = {
    make_devexpl_pval_table(CNP_highlat_gam_devexpl,
			   CNP_highlat_gam_pval, 
			   digits = 3,
			   rownames = TRUE,
			 tab_out_folder,  "sp_table_7.csv")
  },
  sp_table_8 = {
    make_devexpl_pval_table(CNP_lowlat_gam_devexpl,
			   CNP_lowlat_gam_pval, 
			   digits = 3,
			   rownames = TRUE,
			 tab_out_folder,  "sp_table_8.csv")
  },
  sp_table_9 = {
	  make_cnp_gam_cesm_summary_table(cesm_lonlat_info, 
                                     CNP_gam_cesm,
                                     rownames = FALSE,
                                     tab_out_folder,
                                     "sp_table_9.csv")
  },
  sp_table_10 = {
    make_cnp_cv_summary_table(POM_genomes_selected_gam, 
                                    cv_cp,
                              "CP",
                              "C:P Summary",
                                    rownames = FALSE,
                                    tab_out_folder,
                                    "sp_table_10.csv")
  },
  sp_table_11 = {
    make_cnp_cv_summary_table(POM_genomes_selected_gam, 
                                    cv_np,
                              "NP",
                              "N:P Summary",
                                    rownames = FALSE,
                                    tab_out_folder,
                                    "sp_table_11.csv")
  },
  sp_table_12 = {
    make_cnp_cv_summary_table(POM_genomes_selected_gam, 
                                    cv_cn,
                              "CN",
                              "C:N Summary",
                                    rownames = FALSE,
                                    tab_out_folder,
                                    "sp_table_12.csv")
  }


)
