plan  <-  drake::drake_plan(
  # Data -------------------------------------------------
  data = read_file("data/data.csv"),
  control_data = read_file("data/control_data.csv"),
  nutrients = read_file("data/nutrients.csv"),
  co2_data = read_file("data/co2_data.csv"),
  cn_data = make_cn_data(data),
  cn_pond_stats = make_cn_pond_stats(cn_data),
  er_gpp = read_file("data/er_gpp.csv"),
  size_data_2012 = read_file("data/phyto_size_data_2012.csv"),
  size_data_2016 = read_file("data/phyto_size_data_2016.csv"),
  community_data_2012 = read_file("data/rel_abun_phyto_2012.csv"),
  community_data_2016 = read_file("data/rel_abun_phyto_2016.csv"),
  physchem_data = read_file("data/physchem_data.csv"),

  # Analyses ---------------------------------------------
  phyto_stan = readLines(file_in("stan/eqn1_phytoplankton.stan")),
  zoo_stan = readLines(file_in("stan/eqn1_zooplankton.stan")),
  stan_output = run_eqn1_stan(data, list(phytoplankton = phyto_stan,
                                         zooplankton = zoo_stan)),
  posterior_efficiencies = extract_pp_eff(stan_output),
  posterior_kas = extract_pp_par(stan_output, param = "ka_"),
  posterior_kes = extract_pp_par(stan_output, param = "ke_"),
  posterior_phis = extract_pp_par(stan_output, param = "phi_"),
  pond_stats = make_pond_stats(data),
  hierarchical_biomass = plyr::dlply(pond_stats, .(sample),
                                     run_biomass_model),
  biomass_diff = plyr::ldply(names(hierarchical_biomass),
                             calc_biomass_diff,
                             model_list = hierarchical_biomass) %>%
    dplyr::mutate(variable = "biomass"),
  biomass_diff_summary = plyr::ddply(biomass_diff,
                                     .(sample),
                                     calc_biomass_diff_summary),
  cn_ratios = run_cn_model(cn_data),
  x_seq = seq(0, 60, length.out = 200),
  pp_means = extract_pp_means(stan_output, x_seq = x_seq),
  pp_ponds = extract_pp_ponds(data, stan_output, x_seq),
  diff_eff = calculate_diffs(posterior_efficiencies),
  diff_kas = calculate_diffs(posterior_kas, decline = FALSE),
  diff_kes = calculate_diffs(posterior_kes, decline = FALSE),
  ba_co2 = run_ba_co2(co2_data),
  ba_nutrients = run_ba_nutrients(nutrients),
  permanova_community_2012 = run_permanova_community(community_data_2012),
  permanova_community_2016 = run_permanova_community(community_data_2016),
  resid_brm_model = run_residual_model(data, nutrients, stan_output),
  resid_plot_data = make_resid_plot_data(resid_brm_model, data),

  # Figures ----------------------------------------------
  fig_out_folder = dir.create("output/figures/",
                              recursive = TRUE,
                              showWarnings = FALSE),
  # "Warmed, red" [1], "Ambient, blue" [2]
  my_cols_treatment = c(ggsci::pal_npg("nrc")(10)[1],
                        ggsci::pal_jco("default")(10)[1]),
  # phyto (green), zoo (brown)
  my_cols_group = ggsci::pal_npg("nrc")(10)[c(3, 9)],
  phy_png = make_grob_png(file_in("pics/phyto.png")),
  zoo_png = make_grob_png(file_in("pics/zoo.png")),
  fig_1_pdf = make_fig_1(file_out("output/figures/fig_1.pdf"), fig_out_folder,
                         pp_means, my_cols_treatment, phy_png, zoo_png),
  fig_2_pdf = make_fig_2(file_out("output/figures/fig_2.pdf"), fig_out_folder,
                         posterior_efficiencies, posterior_kas, posterior_kes,
                         posterior_phis, my_cols_treatment, phy_png, zoo_png),
  fig_3_pdf = make_fig_3(file_out("output/figures/fig_3.pdf"), fig_out_folder,
                         pond_stats, phy_png, zoo_png, my_cols_treatment),
  # this line below makes internal plot ED Fig 1d only
  # whole schematic was drawn outside of R and
  # manually merged with this internal plot;
  # schematic is provided in pics/figS1.pdf
  ed_fig_1d_pdf = make_internal_ed_fig_1d(file_out("output/figures/ed_fig_1d.pdf"),
                                          fig_out_folder, physchem_data,
                                          my_cols_treatment),
  ed_fig_1_png = generate_png(file_in("pics/ed_fig_1.pdf"),
                              file_out("output/figures/ed_fig_1.png")),
  ed_fig_2_pdf = make_ed_fig_2(file_out("output/figures/ed_fig_2.pdf"),
                               fig_out_folder, data = nutrients,
                               my_cols_treatment = my_cols_treatment),
  ed_fig_3_pdf = make_ed_fig_3(file_out("output/figures/ed_fig_3.pdf"),
                               fig_out_folder, co2_data, my_cols_treatment),
  ed_fig_4_png = generate_png(file_in("pics/ed_fig_4.pdf"),
                              file_out("output/figures/ed_fig_4.png")),
  ed_fig_5_pdf = make_ed_fig_5(file_out("output/figures/ed_fig_5.pdf"),
                               fig_out_folder, data, pp_ponds,
                               my_cols_treatment, my_cols_group),
  ed_fig_6_pdf = make_ed_fig_6(file_out("output/figures/ed_fig_6.pdf"),
                               fig_out_folder, posterior_efficiencies,
                               biomass_diff, phy_png, zoo_png),
  ed_fig_7_pdf = make_ed_fig_7(file_out("output/figures/ed_fig_7.pdf"),
                               fig_out_folder, control_data, my_cols_group),
  ed_fig_8_pdf = make_ed_fig_8(file_out("output/figures/ed_fig_8.pdf"),
                               fig_out_folder, pond_stats, phy_png, zoo_png,
                               my_cols_treatment),
  ed_fig_9_pdf = make_ed_fig_9(file_out("output/figures/ed_fig_9.pdf"),
                               fig_out_folder, cn_pond_stats, phy_png,
                               zoo_png, my_cols_treatment),
  sp_fig_1_pdf = make_sp_fig_inorganic(file_out("output/figures/sp_fig_1.pdf"),
                                       fig_out_folder, ba_nutrients, "NO2_uM",
                                       substitute(mu * "mol " * a * " L"^-1,
                                                  list(a = chemf("NO2-"))),
                                       my_cols_treatment),
  sp_fig_2_pdf = make_sp_fig_inorganic(file_out("output/figures/sp_fig_2.pdf"),
                                       fig_out_folder,
                                       ba_nutrients, "NO3_uM",
                                       substitute(mu * "mol " * a * " L"^-1,
                                                  list(a = chemf("NO3-"))),
                                       my_cols_treatment),
  sp_fig_3_pdf = make_sp_fig_inorganic(file_out("output/figures/sp_fig_3.pdf"),
                                       fig_out_folder,
                                       ba_nutrients, "NH3_uM",
                                       substitute(mu * "mol " * a * " L"^-1,
                                                  list(a = chemf("NO4+"))),
                                       my_cols_treatment),
  sp_fig_4_pdf = make_sp_fig_4(file_out("output/figures/sp_fig_4.pdf"),
                               fig_out_folder, ba_co2,
                               substitute("Daytime CO"[2] *
                                            " influx (" *
                                            mu *
                                            "mol m"^-2 *
                                            " d"^-1 * ")"),
                               my_cols_treatment),
  sp_fig_5_pdf = make_sp_fig_5(file_out("output/figures/sp_fig_5.pdf"),
                               fig_out_folder, cn_ratios, phy_png, zoo_png,
                               my_cols_treatment),
  sp_fig_6_pdf = make_sp_fig_6(file_out("output/figures/sp_fig_6.pdf"),
                               fig_out_folder, data = data,
                               model_list = stan_output,
                               my_cols_treatment = my_cols_treatment),
  sp_fig_7_pdf = make_sp_fig_7(file_out("output/figures/sp_fig_7.pdf"),
                               fig_out_folder, hierarchical_biomass,
                               phy_png, zoo_png, my_cols_treatment),
  sp_fig_8_pdf = make_sp_fig_8(file_out("output/figures/sp_fig_8.pdf"),
                               fig_out_folder, community_data_2012,
                               community_data_2016, size_data_2012,
                               size_data_2016, my_cols_treatment),
  sp_fig_9_pdf = make_sp_fig_9(file_out("output/figures/sp_fig_9.pdf"),
                               fig_out_folder, er_gpp, my_cols_treatment),
  sp_fig_10_pdf = make_sp_fig_10(file_out("output/figures/sp_fig_10.pdf"),
                                 fig_out_folder, pp_means, phy_png, zoo_png,
                                 my_cols_treatment),
  sp_fig_11_pdf = make_sp_fig_11_13(file_out("output/figures/sp_fig_11.pdf"),
                                    fig_out_folder, resid_plot_data, "NO2_uM",
                                    my_cols_group,
                                    substitute(mu * "mol " * a * " L"^-1,
                                               list(a = chemf("NO2-")))),
  sp_fig_12_pdf = make_sp_fig_11_13(file_out("output/figures/sp_fig_12.pdf"),
                                    fig_out_folder, resid_plot_data, "NO3_uM",
                                    my_cols_group,
                                    substitute(mu * "mol " * a * " L"^-1,
                                               list(a = chemf("NO3-")))),
  sp_fig_13_pdf = make_sp_fig_11_13(file_out("output/figures/sp_fig_13.pdf"),
                                    fig_out_folder, resid_plot_data, "NH3_uM",
                                    my_cols_group,
                                    substitute(mu * "mol " * a * " L"^-1,
                                               list(a = chemf("NH4+")))),

  # Tables -----------------------------------------------
  tab_out_folder = {
    dir.create("output/tables/", recursive = TRUE, showWarnings = FALSE)
    "output/tables"
  },
  ed_table_1 = {
    make_ed_table_1(stan_output, tab_out_folder, "ed_table_1.csv")
  },
  sp_table_1 = {
    make_sp_table_1(ba_co2, ba_nutrients, tab_out_folder, "sp_table_1.csv")
  },
  sp_table_2 = {
    make_sp_table_2(resid_brm_model, tab_out_folder, "sp_table_2.csv")
  }
)
